apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml

images:
  - name: redis
    newName: redis
    newTag: latest

namespace: database

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app: redis

secretGenerator:
  - name: redis-secret
    literals:
      - REDIS_PASSWORD=""