apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml

images:
  - name: publisher-image
    newName: publisher
    newTag: latest

namespace: data-migration

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app: publisher

configMapGenerator:
  - name: publisher-config
    literals:
      - GCP_PROJECT_ID=""
      - GCP_BUCKET_NAME=""
      - GCP_PUBSUB_HOST="pubsub-emulator.gcloud.svc.cluster.local:8085"
      - GCP_SUBSCRIPTION_ID=""
      - GCP_TOPIC_ID=""
      - AWS_REGION=""
      - AWS_S3_BUCKET=""
      - GCP_CREDENTIALS="/secrets/svc_account.json"
      - SYSTEM_MAX_WORKERS=5
      - REDIS_ADDRESS="redis.database.svc.cluster.local:6379"
      - SYSTEM_ADMIN_USERNAME=""

secretGenerator:
  - name: publisher-secret
    literals:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - REDIS_PASSWORD=""
      - SYSTEM_ADMIN_PASSWORD=""
  - name: gcloud-service-account-secret
    files:
      - svc_account.json=./secret/svc_account.json