apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml

images:
  - name: data-migration-app-image
    newName: data-migration-app
    newTag: latest

namespace: data-migration

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app: data-migration-app

configMapGenerator:
  - name: data-migration-app-config
    literals:
      - GCP_PROJECT_ID=""
      - GCP_BUCKET_NAME=""
      - GCP_PUBSUB_HOST=""
      - GCP_SUBSCRIPTION_ID=""
      - GCP_TOPIC_ID=""
      - AWS_REGION=""
      - AWS_S3_BUCKET=""
      - GCP_CREDENTIALS=""
      - SYSTEM_MAX_WORKERS=5

secretGenerator:
  - name: data-migration-app-secret
    literals:
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
  - name: gcloud-service-account-secret
    files:
      - svc_account.json=./secret/svc_account.json