apiVersion: v1
kind: Service
metadata:
  name: pubsub-emulator
  namespace: gcloud
spec:
  selector:
    app: pubsub-emulator
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP